"""add table ReviewsSugg

Revision ID: 45b84fcee73a
Revises: 3ea02f01387a
Create Date: 2023-11-02 13:20:59.620202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b84fcee73a'
down_revision = '3ea02f01387a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sugg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sugg_count', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_sugg')
    # ### end Alembic commands ###
