"""add two column redirect_uri & welcome_text in table store

Revision ID: 550b7abb1a98
Revises: 45b84fcee73a
Create Date: 2023-11-02 18:23:55.363373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550b7abb1a98'
down_revision = '45b84fcee73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirect_url', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('welcome_text', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('welcome_text')
        batch_op.drop_column('redirect_url')

    # ### end Alembic commands ###
