"""Init Migrate (add tables stores & user_clicks)

Revision ID: f338321f39d1
Revises: 
Create Date: 2023-11-01 16:10:16.791939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f338321f39d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('max_clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_name')
    )
    op.create_table('user_clicks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_clicks')
    op.drop_table('stores')
    # ### end Alembic commands ###
